// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkQadAQnKgxCP-ndyNYsjFcZKFaUTflwU',
    appId: '1:978792815028:web:0479792ffde98d95bd7ae1',
    messagingSenderId: '978792815028',
    projectId: 'chat-app-8f4fe',
    authDomain: 'chat-app-8f4fe.firebaseapp.com',
    storageBucket: 'chat-app-8f4fe.appspot.com',
    measurementId: 'G-C0TNSJLP8Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRixzQIhZF9kE9pGMtWTlkEikDjN9gFeY',
    appId: '1:978792815028:android:593eb706232893c4bd7ae1',
    messagingSenderId: '978792815028',
    projectId: 'chat-app-8f4fe',
    storageBucket: 'chat-app-8f4fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN01es8_pZHEA6jYOPoqegnq32_XNY9mU',
    appId: '1:978792815028:ios:879d6dbd38c27f13bd7ae1',
    messagingSenderId: '978792815028',
    projectId: 'chat-app-8f4fe',
    storageBucket: 'chat-app-8f4fe.appspot.com',
    iosClientId: '978792815028-tpvdgf9gse3md19fni07vabd34lsvs69.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
